# Generated by Django 5.0.1 on 2024-02-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_Brand',
            field=models.CharField(default='paws', max_length=75),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_picture',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_desc',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_name',
            field=models.CharField(default='ProductName', max_length=50),
        ),
    ]
