# Generated by Django 5.0.2 on 2024-02-19 06:47

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_pro_brand_product_pro_price_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('pm', django.db.models.manager.Manager()),
            ],
        ),
    ]
